const ACTIONS = {
  LOGIN: "LOGIN",
  GET_TOKEN: "GET_TOKEN",
  GET_USER: "GET_USER",
  GET_ALL_USERS: "GET_ALL_USERS",
  GET_ONE_USER: "GET_ONE_USER",
  GET_ALL_DOCTOR: "GET_ALL_DOCTOR",
  SAVE_DETAILS_DOCTOR: "SAVE_DETAILS_DOCTOR",
  GET_DETAIL_DOCTOR: "GET_DETAIL_DOCTOR",
  GET_INFOR_DOCTOR: "GET_INFOR_DOCTOR",
  GET_ALL_TIME: "GET_ALL_TIME",
  GET_SCHEDULE: "GET_SCHEDULE",
  GET_INFOR_ALLCODE: "GET_INFOR_ALLCODE",
  GET_ALL_SPECIALTY: "GET_ALL_SPECIALTY",
  GET_DETAIL_SPECIALTY: "GET_DETAIL_SPECIALTY",
  GET_DOCTOR_SPECIALTY: "GET_DOCTOR_SPECIALTY",
  GET_ALL_CLINIC: "GET_ALL_CLINIC",
  GET_DETAIL_CLINIC: "GET_DETAIL_CLINIC",
  GET_DOCTOR_CLINIC: "GET_DOCTOR_CLINIC",
  GET_DOCTOR_BOOKING: "GET_DOCTOR_BOOKING",
  GET_MY_BOOKING: "GET_MY_BOOKING",
};

export default ACTIONS